### PR TITLE
(GH-429) Save all files before applying changes

### LINKED ISSUE #429: 'Add [tool|addin] from nuget' should save the Cake script if it's already open.
When editing the Cake file, during edit select '*Add [tool|addin] from nuget*' command and add something.
The tool (or addin) will be added to the Cake file as it is, on the disk but not in the file that is currently open.

Example:
72mrwIu3Bj

I see two possible soltions:
* If the file is already open simply add the content to the current file (without saving it) - *not sure if that's possible, though*
* Ask the user to save, before the file is modified.

### PR DESCRIPTION
**Pull request by gep13**
When running the command to add addin/tool/module to a .cake file, make
sure to save any dirty files, before making the change.

Fixes #429

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a if you have a minute, can you take this for a spin and let me know if this addresses the issue that you were seeing?  Thanks

**Comment by nils-a** [comment]
@gep13 no joy. I always get the following messages simultaneously:

Code_-_Insiders_JyVQFN53yw

**Comment by gep13** [comment]
I will try something different. I think I have another extension installed that is preventing me for replicating the problem, but I will keep trying.

**Comment by nils-a** [comment]
@gep13 currently it *feels* like you are trying to save, but "all at once" if you know what I mean. I *feels* like you are trying to modify the file on disc, at the same time you are trying to save the file to disc.

**Comment by gep13** [comment]
@nils-a thanks for the assist with this, really appreciate it!

**Pull request merged**
