### PR TITLE
(GH-473) checking the latest available Cake.Tool

### LINKED ISSUE #473: update-checks for Cake Tool only works with .NET 5 installed
as discussed on stream, currently the update check (from #460 ) is done using `dotnet tool search cake.tool` . `dotnet tool search` is only available on .NET 5.

While the code is not visibly failing, no version check is performed as long as .NET 5 is not available.

An alternative to checking existing versions using `dotnet` could be accessing either
`https://azuresearch-usnc.nuget.org/autocomplete?id=cake.tool&prerelease=false` or `https://azuresearch-usnc.nuget.org/query?q=Cake.Tool&prerelease=false`

### PR DESCRIPTION
**Pull request by nils-a**
version on nuget, rather than calling "dotnet tool search".
This was done because running "dotnet tool search" would only
work starting with .NET 5.

fixes #473

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a thanks for submitting this.  Having thought about it, I think there is a little bit more work that we need to do here...

The URL that you are using here is subject to change, it isn't fixed.  The only URL that is fixed is the one to the service index, i.e: https://api.nuget.org/v3/index.json From there, you can find the URL's to the services that you are interested in.  You can sort of see this in action within the `fetchPacakgeVersions.ts` file (https://github.com/cake-build/cake-vscode/blob/2da55a8938/src/addPackage/actions/fetchPackageVersions.ts) when it is finding the available versions of the addins/modules/tools that can be added to the Cake Script.

Ideally, if we were going to go down this route, we would look to use a similar mechanism here, rather than hard-coding the URL.

Does that make sense?

**Comment by nils-a** [comment]
@gep13 Agreed. Will re-work this later.

**Comment by nils-a** [comment]
@gep13 I have introduced a little helper to get the correct service endpoints and modified my code, as well as `fetchPackageVersion` and `fetchCakePackages`

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@nils-a your changes have been merged, thanks for your contribution 👍

**Pull request merged**
