### PR TITLE
Adds debug command as option to guided install.

### LINKED ISSUE #42: Add aggregate command
i.e. a single command to add all standard Cake files.

Similar to the output from the Cake Yeoman Generator

### PR DESCRIPTION
**Pull request by agc93**
This should resolve #42 since #45 covers the remaining logic

NOTE: Also includes initial refactoring in preparation for #45

### CODE REVIEW

**Comment by agc93** [comment]
Hey @gep13 I started work on this (on the branch) before I saw you merged the PR from yesterday. Hopefully this approach doesn't muck up too much :smile:

**Comment by agc93** [comment]
@gep13 Had a chance to try this out?

**Comment by gep13** [comment]
That is my plan for tonight, to get this new version out the door.

**Comment by gep13** [comment]
@agc93 needed a rebase, so merged here: https://github.com/cake-build/cake-vscode/commit/37f1d9f638ee4ef880adc51cb16e21cfdcf892ac

**Pull request closed without merging**
