### PR TITLE
(GH-470) Add check for which debugger to install

### LINKED ISSUE #470: When running "Cake: Install to workspace", installing debug-dependencies should ask
which runner should be installed.

Currently though, the runner for .NET Framework is always installed.

There's also a *TODO* in the codebase for exactly this: https://github.com/cake-build/cake-vscode/blob/240270bcbbf408570389f218080a681c81eb41ed/src/install/actions/installCake.ts#L73

### PR DESCRIPTION
**Pull request by gep13**
When installing Cake to the current workspace, if installed debug
support, check which type of debugger they would like to install.

Refactored a little bit of code to get things to work, I suspect that
there are further refactorings that could be done.

Fixes #470

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a having done this, I suspect that there is some overlap between your PR here:

https://github.com/cake-build/cake-vscode/pull/468

So there will likely need to be some resolving of merge conflicts when either one is merged.

Would love to get some feedback on this.  Thanks

**Comment by gep13** [comment]
The install Cake to workspace now looks like this:



And the install debug dependencies now looks like this:

**Review by nils-a — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@nils-a thanks for the review!

**Pull request merged**
