### PR TITLE
(GH-409) "Run Task" now always installs .NET Tool

### PR DESCRIPTION
**Pull request by nils-a**
unless configured not to, using `cake.taskRunner.installNetTool`
set to `false`.

This was done by replacing the `ShellExecution` with a `CustomExecution`.

### CODE REVIEW

**Comment by gep13** [comment]
@nils-a this looks really good as well!

Are you in a position to update this PR, based on #467 getting pulled in.  Seems like there were a few moving parts in the that PR, that affect this one.

**Comment by nils-a** [comment]
I'm only at the phone currently (really like the GitHub App..)
But I will update this later today.

**Comment by gep13** [comment]
>@nils-a said...
really like the GitHub App..

Agreed, it is very good!

That would be great, thank you very much!

**Comment by nils-a** [comment]
@gep13 If it's ok with you I'll wait for #471 and rebase onto that. There's some really good changes there.

**Comment by gep13** [comment]
@nils-a totally fine with me 😄 I have merged that PR now.

**Comment by nils-a** [comment]
@gep13  it was much less work than I had anticipated 🤣

**Review by gep13 — APPROVED** [review]
LGTM

**Comment by gep13** [comment]
@nils-a thank you very much!

**Pull request merged**
