### PR TITLE
feat(commands): module command to add packages from nuget

### PR DESCRIPTION
**Pull request by jrgcubano**
- Command to add Module packages from NuGet to default tools/Modules/packages.config or the path specified on cake.config. 
- Removed all build warnings from #74 
- Styled code with prettier 
- Tests from single point (extension.test). I will add more tests on next release...

vscode-cake-module
- Implement #76

### CODE REVIEW

**Comment by patriksvensson** [comment]
@jrgcubano Awesome work! 👍

**Comment by gep13** [comment]
@jrgcubano  A couple questions, on this...

When you say that "Styled code with prettier" how did you do this?  Was this using a tool, or an extension?

For future work, it would be good to have some of these things as individual commits, so that it is easier to look back on what has changed.  i.e. a commit for tidying up build warnings/errors, a commit for changing code style, etc.

**Comment by jrgcubano** [comment]
@gep13 It's a tool and an extension too. I used automatically the extension (Prettier code formating for vscode). Maybe we can add a command on package.json with a pre-commit step to format the staged code or follow some guidelines.

You're right about individual commits (Sorry for that). I will separate it better next time. 👍

**Comment by gep13** [comment]
@jrgcubano seems like there are lots of Prettier extensions:

https://marketplace.visualstudio.com/search?term=prettier&target=VSCode&category=All%20categories&sortBy=Relevance

Can you confirm which one you are using?  I would like to also install the same.

> You're right about individual commits (Sorry for that). I will separate it better next time.

No need to apologise.  Sounds like we are on the same page, so it's all good 😄

**Comment by jrgcubano** [comment]
@gep13 https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by gep13** [comment]
@jrgcubano thank you

**Pull request merged**
