### PR TITLE
(GH-376) CodeLens debugging using global tool

### PR DESCRIPTION
**Pull request by nils-a**
@gep13 I did two things different to what you did in the video:
* I removed the `windows` property from settings and added an object with `default` and `win32` like I've done with the launchCommand.
* I fixed the reason debugging did not work during the video: I removed the quotes (`"`) from the target. Not sure why this is a problem but debugging does not work (any longer) when they are present.

### CODE REVIEW

**Comment by nils-a** [comment]
@gep13 I've also started adding the global tool to the "install debug dependencies" - however currently not in this PR, as I had the impression that it would be a bit much :-)
Also, that's probably not done, as installing CoreCLR is done in quite some places..

The work is currently here: https://github.com/nils-a/cake-vscode/compare/feature/debug-core-tool...nils-a:feature/install-global-tool (as a branch, based on the branch from this PR)

**Comment by gep13** [comment]
@nils-a is this ready for review, or is it still in draft?

**Comment by nils-a** [comment]
@gep13 I removed the draft status and included the installation of the NET core global tool. So feel free to review.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@nils-a thank you very much for getting this added!

**Pull request merged**
