### PR TITLE
Add missing configuration key in package.json

### PR DESCRIPTION
**Pull request by fabionuno**
Adding this information enables comment commands in editor

### CODE REVIEW

**Comment by gep13** [comment]
@fabionuno this looks good to me!

Can you provide an example of how this addition would be used, and in what context?  Do you think it would make sense to update the documentation page for Cake to show how this addition could be used?

http://cakebuild.net/docs/editors/vscode

If so, would you be in a position to submit a pull request?  Thanks for your contribution!

**Comment by fabionuno** [comment]
This configuration is necessary so that vscode identifies if the specified language supports line and block comments.
With this information defined we have the ability to use the "&#8984;/" (line comment) and "&#8679;&#8997;A" (block comment) commands when editing Cake files.



I think it would not be necessary to update Cake's documentation because this is a common functionality of vscode.

**Comment by gep13** [comment]
@fabionuno thanks for getting back to me.  This has been merged in, and I think @patriksvensson has pushed a new version of the extension.

Thanks again for your contribution!

**Comment by patriksvensson** [comment]
@gep13 @fabionuno Yes, version 1.1 is now available :smile:

**Pull request merged**
