### PR TITLE
feat(commands): addin and tool commands to add packages from nuget

### PR DESCRIPTION
**Pull request by jrgcubano**
vscode-cake-directive

### CODE REVIEW

**Comment by jrgcubano** [comment]
Much of the code is from the nuget extension for vscode. If I take a little more time, I'll try to add some tests on other pull request If I manage to run the tests on the project, which I have not been able to do.

**Comment by gep13** [comment]
@jrgcubano WOW!

This is amazing!

A couple quick questions...

When you say:

> Much of the code is from the nuget extension for vscode

What is the license associated with that code?  We need to make sure that we are not violating anything here, and we should also add some credit somewhere indicating where this code comes from.

Am I right in saying that this isn't actually resolving the packages into the tools and tools/addins folder?  i.e. it is updating the required .cake file, and resolving the actual nuget package will be done when the build is ran?  This is perfectly fine by the way, I just want to check.

Could we also do the same for adding Modules into the current system?  This would require updating a packages.config file, rather than a .cake file, but it should be very similar.  We could do this as a separate PR if you wanted.

If we can get the first question answered, then I would be more than happy to get this pulled into the code base.  Epic work!

**Comment by jrgcubano** [comment]
Hi @gep13. 

- They use a [MIT license](https://github.com/jmrog/vscode-nuget-package-manager/blob/master/LICENSE).  We could split a bit more the README.md and add more sections like cake project (Contributing, License, Thanks, Code of Conduct, Contribution License Agreement, NET Foundation, Addtional Resources, etc). So we could add part of the credits in a section like
   - **Additional Resources**
     - Nuget commands based on [vscode-nuget-package-manager](https://github.com/jmrog/vscode-nuget-package-manager)

- Only the file is modified. Regarding the modification, I had tried several models to keep the structure with the existing directives and comments, etc. But since you do not have control over the order of the directives (tool addin, addin, tooll, etc), I discard it. So, it is basically added to the beginning of the file if the directive does not exist, and otherwise the line is updated.
- I could do the modules in another pull request and complete the tests.

Thank you!

**Comment by gep13** [comment]
Relates to #75

**Comment by gep13** [comment]
@jrgcubano Thanks again for doing this work!  It really is amazing!

**Comment by gep13** [comment]
@jrgcubano I have updated the README.md to include a `Thanks` section, and mentioned the other extension and it's author.

**Comment by jrgcubano** [comment]
@gep13 nice!

**Pull request merged**
